# -*- coding: utf-8 -*-
"""DataLogging_Performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ELWL8XZf0PQqWaIxZANwd9F_TYI4nDf
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression
import re
import os


from google.colab import drive
drive.mount('/content/drive')

def compare_memory_usage_single(df, name):
    stats = []

    def fit_slope(x, y):
        m, b = np.polyfit(x, y, 1)
        return m, b

    def convert_to_kb(bytes_value):
        return bytes_value / 1024

    df['Time_Since_Start_Minutes'] = (df['datetime'] - df['datetime'].min()).dt.total_seconds() / 60

    df['MEM_USED_KB'] = df['Arp.Plc.Eclr/code.USER_PART_DT.MEM_USED'].apply(convert_to_kb)
    df['MEM_TOTAL_KB'] = df['Arp.Plc.Eclr/code.USER_PART_DT.MEM_TOTAL'].apply(convert_to_kb)

    used_memory_rate = (df['MEM_USED_KB'].diff().mean()) / (df.index[1] - df.index[0]) if len(df) > 1 else 0

    initial_used_kb = df['MEM_USED_KB'].iloc[0]
    initial_total_kb = df['MEM_TOTAL_KB'].iloc[0]
    initial_memory_percent = (initial_used_kb / initial_total_kb) * 100

    stats.append({
        'Scenario': name,
        'Used Memory Rate (KB/min)': used_memory_rate,
        'Initial Memory Used (KB)': initial_used_kb,
        'Initial Memory Used (%)': round(initial_memory_percent, 2)
    })

    stats_df = pd.DataFrame(stats)
    print(stats_df)

folder_path = '' # Define path name

db_files = [f for f in os.listdir(folder_path) if f.endswith('.db')]

for db_file in db_files:
    db_path = os.path.join(folder_path, db_file)

    conn = sqlite3.connect(db_path)

    query = 'SELECT * FROM log_all_3491412257'
    df = pd.read_sql_query(query, conn)

    df['Total_Exec_Duration'] = (
        df['Arp.Plc.Eclr/code.ESM_DATA1.ESM_INFOS[1].TASK_INFOS[1].LAST_EXEC_DURATION'] +
        df['Arp.Plc.Eclr/code.ESM_DATA1.ESM_INFOS[2].TASK_INFOS[1].LAST_EXEC_DURATION']
    )

    df['datetime'] = pd.to_datetime(
        df['Arp.Plc.Eclr/code.RTC_DT.YEAR'].astype(str) + '-' +
        df['Arp.Plc.Eclr/code.RTC_DT.MONTH'].astype(str).str.zfill(2) + '-' +
        df['Arp.Plc.Eclr/code.RTC_DT.DAY'].astype(str).str.zfill(2) + ' ' +
        df['Arp.Plc.Eclr/code.RTC_DT.HOURS'].astype(str).str.zfill(2) + ':' +
        df['Arp.Plc.Eclr/code.RTC_DT.MINUTES'].astype(str).str.zfill(2) + ':' +
        df['Arp.Plc.Eclr/code.RTC_DT.SECONDS'].astype(str).str.zfill(2)
    )

    compare_memory_usage_single(df[100:-100], db_file)
    conn.close()

def compare_cycle_times_single(df, name):
    stats = []

    df['Time_Since_Start_Minutes'] = (df['datetime'] - df['datetime'].min()).dt.total_seconds() / 60
    df['Total_Exec_Duration'] = df['Total_Exec_Duration'] / 2

    stats.append({
        'Name': name,
        'Mean': df['Total_Exec_Duration'].mean(),
        'Max': df['Total_Exec_Duration'].max(),
        'Std': df['Total_Exec_Duration'].std(),
    })

    stats_df = pd.DataFrame(stats)
    print(stats_df)

    cmap = plt.get_cmap("coolwarm")

    plt.figure(figsize=(14, 8))
    colors = cmap(df['Total_Exec_Duration'] / df['Total_Exec_Duration'].max())
    plt.scatter(df['Time_Since_Start_Minutes'], df['Total_Exec_Duration'], color=colors, alpha=0.7)
    plt.plot(df['Time_Since_Start_Minutes'], df['Total_Exec_Duration'].rolling(window=200).mean(), color='black', linestyle='--')
    plt.title(f"{name} Cycle Time Over Time", fontsize=16)
    plt.ylabel('Cycle Time (ms)', fontsize=14)
    plt.xlabel('Time Since Start (minutes)', fontsize=14)
    plt.grid(True)
    plt.legend(fontsize=12)
    plt.tight_layout()
    plt.show()

folder_path = '' #define pathname

db_files = [f for f in os.listdir(folder_path) if f.endswith('.db')]


for db_file in db_files:
    db_path = os.path.join(folder_path, db_file)

    conn = sqlite3.connect(db_path)

    query = 'SELECT * FROM log_all_3491412257'
    df = pd.read_sql_query(query, conn)

    df['Total_Exec_Duration'] = (
        df['Arp.Plc.Eclr/code.ESM_DATA1.ESM_INFOS[1].TASK_INFOS[1].LAST_EXEC_DURATION'] +
        df['Arp.Plc.Eclr/code.ESM_DATA1.ESM_INFOS[2].TASK_INFOS[1].LAST_EXEC_DURATION']
    )

    df['datetime'] = pd.to_datetime(
        df['Arp.Plc.Eclr/code.RTC_DT.YEAR'].astype(str) + '-' +
        df['Arp.Plc.Eclr/code.RTC_DT.MONTH'].astype(str).str.zfill(2) + '-' +
        df['Arp.Plc.Eclr/code.RTC_DT.DAY'].astype(str).str.zfill(2) + ' ' +
        df['Arp.Plc.Eclr/code.RTC_DT.HOURS'].astype(str).str.zfill(2) + ':' +
        df['Arp.Plc.Eclr/code.RTC_DT.MINUTES'].astype(str).str.zfill(2) + ':' +
        df['Arp.Plc.Eclr/code.RTC_DT.SECONDS'].astype(str).str.zfill(2)
    )

    compare_cycle_times_single(df[100:], db_file)
    conn.close()

def compare_cpu_usage_single(df, name):

    cpu_usage_avg = df['Arp.Plc.Eclr/code.cpu_all']


    total_points = len(cpu_usage_avg)
    outliers = cpu_usage_avg[(cpu_usage_avg > cpu_usage_avg.quantile(0.95)) | (cpu_usage_avg < cpu_usage_avg.quantile(0.05))]
    num_outliers = len(outliers)
    percentage_outliers = (num_outliers / total_points) * 100

    stats = {
        'Name': name,
        'Mean': cpu_usage_avg.mean(),
        'Max': cpu_usage_avg.max(),
        'Std': cpu_usage_avg.std()
    }


    stats_df = pd.DataFrame([stats])
    print(stats_df)


    plt.figure(figsize=(14, 6))
    plt.plot(cpu_usage_avg, label=f'{name} - Average CPU Usage', color='blue')


    avg_line = [cpu_usage_avg.mean()] * len(cpu_usage_avg)
    plt.plot(cpu_usage_avg.index, avg_line, label='Average Line', linestyle='--', color='orange')


    x = cpu_usage_avg.index.values.reshape(-1, 1)
    y = cpu_usage_avg.values
    reg = LinearRegression().fit(x, y)
    reg_line = reg.predict(x)
    plt.plot(cpu_usage_avg.index, reg_line, label='Regression Line', linestyle='-', color='red')

    plt.title(f'Average CPU Usage Trend Over Time - {name}')
    plt.xlabel('Index')
    plt.ylabel('Average CPU Usage (%)')
    plt.grid(True)
    plt.legend()
    plt.show()

folder_path = '' #define path


db_files = [f for f in os.listdir(folder_path) if f.endswith('.db')]



for db_file in db_files:
    db_path = os.path.join(folder_path, db_file)


    conn = sqlite3.connect(db_path)


    query = 'SELECT * FROM log_all_3491412257'
    df = pd.read_sql_query(query, conn)

    df['Total_Exec_Duration'] = (
        df['Arp.Plc.Eclr/code.ESM_DATA1.ESM_INFOS[1].TASK_INFOS[1].LAST_EXEC_DURATION'] +
        df['Arp.Plc.Eclr/code.ESM_DATA1.ESM_INFOS[2].TASK_INFOS[1].LAST_EXEC_DURATION']
    )

    df['datetime'] = pd.to_datetime(
        df['Arp.Plc.Eclr/code.RTC_DT.YEAR'].astype(str) + '-' +
        df['Arp.Plc.Eclr/code.RTC_DT.MONTH'].astype(str).str.zfill(2) + '-' +
        df['Arp.Plc.Eclr/code.RTC_DT.DAY'].astype(str).str.zfill(2) + ' ' +
        df['Arp.Plc.Eclr/code.RTC_DT.HOURS'].astype(str).str.zfill(2) + ':' +
        df['Arp.Plc.Eclr/code.RTC_DT.MINUTES'].astype(str).str.zfill(2) + ':' +
        df['Arp.Plc.Eclr/code.RTC_DT.SECONDS'].astype(str).str.zfill(2)
    )

    compare_cpu_usage_single(df, db_file)

    conn.close()